### ISSUE TITLE
Enhancing the OCR Application: Usability, Comparison, and Multilingual Support

### ISSUE THREAD

**Issue by Mokhyy** [egdels/makeacopy#46]
Hello,

Thank you for developing such a great program. It runs smoothly and is very useful. I have a few suggestions that could make it even more professional:

1. **Add a pre‑processing menu** – Before entering the photography environment, present a menu that lets the user choose between  
   * OCR on an existing photo, or  
   * OCR on a newly captured photo.  
   Each option would follow its own initial workflow, but both would converge on the same processing pipeline.

2. **Side‑by‑side comparison view** – Allow the user to view the extracted text alongside the original photo in a single interface. This makes it easy to verify that the OCR output matches the text in the image.

3. **Copy button** – Place a “Copy” button beneath the text field that contains the detected text, enabling the user to copy the entire result with one click.

4. **Editable text field** – After implementing the comparison view, make the text field editable. Users can then correct any discrepancies between the image and the OCR output, giving them finer control over the final text.

5. **Support for Persian and Arabic** – Adding Persian and Arabic language support would be highly valuable, as these languages are frequently needed.

6. **Package selection bug** – When the “Best” package is imported, the “Fast” package disappears and is replaced by “Best.” It would be better if both packages could be selected independently, rather than one overwriting the other.

I hope these suggestions are helpful. Thank you again for your hard work on this useful program.

**Comment by egdels** [comment]
Hi @Mokhyy . Thanks for your comments. I’m not yet sure if I want to take all of that into account. What will definitely be included is a mode for editing the OCR result. The code for it is mostly done but still hidden behind a feature flag because it’s not fully error-free yet. I also want to add support for Arabic and Persian, of course - but that will take some more time.

**Comment by Mokhyy** [comment]
Hi @egdels 

Thank you for reading my feedback and responding so quickly.
The few items you’ve considered are excellent and represent a step forward in advancing this great program.

I tried the new version and would like to report a bug I encountered recently. This bug is present in both **2.1.1** and **2.2.0**.

When using the **OpenCV robust (high quality)** mode, if I input an image with a completely black background (AMOLED) and white text, the OCR result is completely unrelated and incorrect. The problem does not occur when the background of the paper or image containing the text is white.

Additionally, when the background is pure black, the other two modes—**Original** and **OpenCV quick**—process the text without any issues and produce correct results.

I’m not sure whether this is a bug or if I have selected the wrong text‑recognition mode for this particular case.

**Comment by egdels** [comment]
Hi @Mokhyy ,

thank you again for your detailed feedback and for testing the new versions – that’s really helpful.

What you’re seeing is very likely a limitation of the current OpenCV robust (high quality) pipeline, not a wrong mode choice on your side. Robust mode applies quite a bit of preprocessing (contrast normalization, denoising, local thresholding, etc.) and it is mainly tuned for “classic” document photos with dark text on a lighter background.

On images with a pure black background and white text (AMOLED style) this heavy preprocessing can actually make things worse:
the text contours may get distorted or the polarity can end up effectively inverted in a way that confuses Tesseract, so it produces garbage output. The other two modes (“Original” and “OpenCV quick”) do much less aggressive preprocessing and therefore handle this special case better.

So:

You did not pick the wrong mode – this is a real edge case for Robust mode.

For now, the best workaround is to use Original or OpenCV quick for AMOLED-black / white-text images.

I’ll treat this as a bug/limitation in the Robust pipeline and see if I can add a special handling for “inverted” / pure-black backgrounds (or automatically fall back to a different mode in that scenario).

If possible, could you share an example image (with any sensitive text redacted/blurred) that shows this behaviour? That would help a lot in testing a fix.

Thanks again for your time and for pushing MakeACopy forward with this kind of detailed report!

**Comment by Mokhyy** [comment]
I’ll send you the results for each mode in a separate text file, and I’ll attach the images themselves so the text field doesn’t get cluttered.  

[Test.txt](https://github.com/user-attachments/files/23546537/Test.txt)

**Sample 1**  

<img width="1846" height="972" alt="Image" src="https://github.com/user-attachments/assets/165490c9-ced4-4ac4-9e19-02df3c013e05" />
<img width="1702" height="830" alt="Image" src="https://github.com/user-attachments/assets/ac476fab-ad6f-48b9-b67d-0c9f19af3c9e" />

**Sample 2**

<img width="1097" height="1309" alt="Image" src="https://github.com/user-attachments/assets/6231e639-a6e3-44cc-a9dd-7aea205b8a7b" />




If you need any further testing anywhere in the app, I’d be happy to help. Since my native language is Persian and the app currently doesn’t support it, I can only provide feedback on the English language model. However, I’m ready to assist with testing any core functionality of the application whenever needed.

**Comment by egdels** [comment]
Thank you very much! Next, I will implement the accessibility mode. After that I’ll work on additional languages. I think Arabic and Persian are a good start. I’ll be happy to come back to your offer then. I will continue improving the OCR robust mode alongside that.

**Comment by egdels** [comment]
Hi @Mokhyy . I hope you’re still interested in the project. I’ve started working on Persian and Arabic support. Here’s an example:

Input PDF: [test_persian_inverted.pdf](https://github.com/user-attachments/files/24345693/test_persian_inverted.pdf)

Output PDF (OCR robust mode):

[DOC_20251226_104551.pdf](https://github.com/user-attachments/files/24345718/DOC_20251226_104551.pdf)

[DOC_20251226_104551.txt](https://github.com/user-attachments/files/24345719/DOC_20251226_104551.txt)

I’m hoping to provide a testable version around the New Year and would really appreciate your help with testing.

Best regards

**Comment by Mokhyy** [comment]
Hello — thank you for adding Persian to the app so quickly. I really appreciate it.
I tested the Persian language feature and I think it works very well for a first release. Although I encountered a few functional issues with the OCR, I can’t describe them precisely yet because they need more testing. However, I did find one definite problem which I will describe for you.

I tested the text-matching (OCR) on images inside a PDF and found that OCR works well overall, but there is a problem with the ordering of letters inside each word in pdf. Instead of the letters in a word appearing in order 1, 2, 3, 4, 5, their order is
 5, 4, 3, 2, 1. This issue applies to each individual word separately. However, the order of words within a sentence is correct — the words appear in the proper sequence relative to each other.
(This issue does not appear in the output TXT file; it only occurs in the PDF output.)

To give an equivalent example in English, it looks like:

Are you ok

era uoy ko

I am attaching a sample PDF and its TXT so you can compare the text inside the PDF with the text file.


[DOC_20251226_185443.pdf](https://github.com/user-attachments/files/24348563/DOC_20251226_185443.pdf)


[DOC_20251226_185443.txt](https://github.com/user-attachments/files/24348565/DOC_20251226_185443.txt)

**Comment by egdels** [comment]
Hello @Mokhyy . You’re right. I’ve already fixed the issue with the ‘era uoy ko’ locally and created my example using the fixed version. The prerelease on GitHub still contains the bug, as do a few other things 😉. I’ll ping you once the next release candidate is available. Thanks a lot for your feedback.

**Comment by egdels** [comment]
Hello @Mokhyy . The next release candidate is ready, and I’m looking forward to your feedback. In addition to the overall OCR quality, I’m particularly interested in whether the fonts are clearly readable in the generated PDF. In some scenarios, the color filters and DPI settings for Persian and Arabic might be a bit too aggressive. I have already conservatively disabled stain removal. In the OCR settings, dictionary-based post-processing can be disabled; it is turned on by default. There is now also an option to load existing PDFs into MakeACopy, which should make testing easier.

Thank you very much for your help!

https://github.com/egdels/makeacopy/releases/tag/v2.4.0-rc2

**Comment by Mokhyy** [comment]
Hello,

I checked and saw that the "era uoy ko" issue has been fixed. Thank you so much. Now I can easily convert my photos to text.

I think the next step should be to add a set of features separate from the OCR engine’s performance. Optimizing the OCR itself requires engineering work and I personally don’t have ideas to improve its quality, and I think the OCR performance of the app is currently acceptable. Right now there are several features that, if added, would make the app much easier and more professional to use:

1. Make the text field editable.  
2. Add a “copy all text” button next to the text field.  
3. Place the text field next to the image so the user can compare the text in the image with the extracted text and match them.  
4. Allow the user to manually adjust the position where the extracted text is overlaid on the image so they can place the text exactly where it belongs.  
5. Let the user select multiple images and have the app process them in the order they were selected.  
6. Increase customization for preprocessing features and provide options for image preprocessing, plus allow creating profiles to save multiple preprocessing presets for different conditions.  
7. Add a preprocessing feature called “background removal” that, when enabled, makes the preprocessing function separate image areas that have high contrast with the background and feed only those regions containing text to the OCR.

Thanks for reading this far. The most important improvements now are items 1–5 and they have higher priority than improving the OCR engine or preprocessing, because—as I said—improving the OCR engine requires engineering effort and various techniques. (These are my priorities; I ranked them this way because I don’t know much about OCR at the moment.)

**Comment by egdels** [comment]
Hello @Mokhyy . Thank you very much.
There is still an issue with the OCR post-processing that teastrainer reported in 

https://github.com/egdels/makeacopy/issues/50

Once I have fixed that, I will create the release.

Regarding your points 1, 2, and 4: I am working on a review mode that is currently hidden behind a feature flag. Here are two screenshots:

<img width="1080" height="2280" alt="Image" src="https://github.com/user-attachments/assets/5c9f5142-c687-4801-9e78-ea88ef9bf790" />

<img width="1080" height="2280" alt="Image" src="https://github.com/user-attachments/assets/8ca6d544-d1fe-4798-ab14-667b14be6f38" />

Best regards,
Christian

**Comment by Mokhyy** [comment]
Hello,

This is really a very well-designed and clever feature, and adding it to the project would truly elevate the project by several levels.
I'm eager to see this feature in the next release.

May I suggest one more idea?

I have another suggestion to make the app more professional: for multilingual texts (which are very common in my textbooks — most of my textbooks are multilingual), add a "+" option so the user can select a second language. When the user selects a second language, both OCR engines should run together (or on low-RAM devices, run one first and then the other). The outputs should then be overlaid into a single unified text.

For example, if a text mixes Persian and English — say the sentence starts with four Persian words, then two English words, then five Persian words — the Persian OCR should recognize the first four and the last five words, leaving the two English words blank (replacing them with spaces) and know that those two words belong to another language and do not exist in Persian. Then the English OCR should recognize those two words and leave the Persian parts blank (using spaces). After that, a function or system separate from the two OCRs should merge the two partial outputs into one complete text by overlaying them.

If you think of a better approach for multilingual recognition, please tell me — I might be able to help. This feature is very important and I personally feel its absence.

Thank you for continuing to develop this promising and high-potential app

**Comment by egdels** [comment]
Hello @Mokhyy . I need a bit more time for the OCR review. It will also be easier once the other improvements are finished first. Release 2.4.0 will include basic support for Persian and Arabic. The following release will then support using two languages at the same time, for example Persian and English. I will provide another prototype at that point.

Thank you very much for your interest in the project and for your suggestions.

**Comment by egdels** [comment]
Hi @Mokhyy . I’ve put together a release candidate for 2.4.1. Feel free to have a look.

https://github.com/egdels/makeacopy/releases/tag/v2.4.1-rc3

**Comment by Mokhyy** [comment]
Great, great, really great

You really nailed the review section. Congratulations — I tested it and really enjoyed the review design.

Now I want to tell you a issues I found


Review → box → split (Just for RTL — Persian/Arabic)
In the review section, the split feature for right-to-left languages like Persian has a problem: when I split a Persian word, the image and its dimensions split correctly, but in the text of layout, instead of splitting the word from right to left, it splits from left to right. The first letters of the word appear at the end, and the last letters appear at the beginning.
(Again — the visual splitting is detected correctly, but the problem is in the text splitting ( just in layout/ document , not in text .)
I also noticed that the reordering of word parts does not happen in text rendering itself, only in the text that exists in the layout.

This issue does not occur in left-to-right languages (English); it happens in right-to-left languages (Persian).  
To make it clearer, here is an example:

Example
Splitting a word in the layout
"سیگنال" ← "نال", "سیگ"
instead of 
"سیگنال" ← "سیگ", "نال"

Suggestion

- Ability to change the width and height of the squares
- Ability to add squares


For now I don't have a better suggestion, but I'll keep thinking about what the app needs to be complete.

I'll do more tests and will let you know

**Comment by egdels** [comment]
Hi @Mokhyy,

thank you very much for the detailed report and for the kind words — I’m really glad to hear that you enjoyed the review mode. Your feedback is extremely valuable, especially for RTL languages.

You are absolutely right about the split behavior for Persian/Arabic in layout mode:

* The visual split (boxes and geometry) is handled correctly.
* The issue is in the text-layer split logic, which currently assumes a left-to-right ordering when splitting words.
* As you correctly observed, this does not affect the plain text output — only the layout/document representation.

The split logic needs to become direction-aware so that RTL languages are split from right to left.

Regarding your suggestions:

* Changing box width/height: noted — this fits well with the review concept, but requires some careful UI/UX work.
* Adding boxes manually: also a good idea and conceptually aligned with the review mode, though a bit more involved. I’ll keep it in mind once the core review interactions are fully stable.

For now, my priorities are:

* Fix the RTL split behavior in layout mode
* Release the review feature
* Further stabilize the review feature based on real-world feedback like yours

Thanks again for testing so thoroughly and for thinking along with the project. Please keep the reports coming — especially for Persian/Arabic edge cases, this kind of feedback is incredibly helpful.

If you’re okay with it, I’d like to acknowledge your contributions by adding you to the Hall of Fame in the README.

Best regards
Christian

**Comment by Mokhyy** [comment]
Hi @egdels 
thanks for continuing to develop such a useful project. To be honest, I really want this project to grow and become complete, because there is a real lack of this kind of app on Android and especially among open‑source projects, and I have been looking for this app for a long time. OCR apps that correctly recognize Persian are very rare and have low accuracy, or if they are accurate they work online.

Thanks for wanting to acknowledge me, but it’s still too early to put my name on it. There’s still a lot of work left on our app and we should focus on that.

I reviewed it again and found a new issue in the review section.

In the re‑ocr section, when we re‑ocr a word that had previously been recognized correctly, the new recognition is completely wrong.

Description
I think this problem happens because the boxes are not yet matched with the OCR and the part of the box that should be sent to the OCR engine is not being sent correctly. (It’s as if the connection between the OCR and the box exists but is incomplete.) That is, when the boxes are first placed they sit correctly in their positions, but when we try to OCR them from the review area, it seems the OCR is not being taken from the same box and passed to the engine. Therefore, if we re‑ocr a word that was previously correct, it returns results completely different from what is in the document.

The issue occurs in both RTL (Persian) and LTR (English); it’s language‑independent.


Note

 in my view , All the OCR engine needs to do, is decide what belongs to its language and what does not. If something belongs to its language it should return it correctly, and if something does not belong to its language it should return nothing and leave the field empty. That defines the accuracy of an OCR engine.

Suggestion

Also — it would be great to add a setting for the OCR engine called “threshold” so the user can choose the confidence level they want the engine to output and filter out everything below it. For example, if the user sets the threshold to 60%, any boxes with less than a 60% confidence score from the engine would remain empty and not be filled. Only boxes scoring above 60% would be populated. (This would greatly help filter results and save time during review and editing.)

**Comment by egdels** [comment]
Hello @Mokhyy . Could you provide a sample PDF and specify which word(s) are not being detected by the re-OCR process?

**Comment by Mokhyy** [comment]
I figured out where the problem is!!!

I rechecked the issue and tested it with two different samples:
1. White background, black text
2. Black background, white text

I found that re-ocr worked fine for (1) but produced unrelated results for (2). So I checked the recognition mode and discovered the problem: in (2), when I used recognition modes other than "opencv robust," the text recognition became irrelevant and low-quality. Therefore, I concluded that the problem is not with re-ocr itself, but that in the review stage re-ocr does not apply the recognition mode, which causes the drop in recognition quality.

https://github.com/user-attachments/assets/26a9c636-6902-40bf-bb57-3dc7dfdaee1c

**Comment by egdels** [comment]
Hello @Mokhyy . Nice catch. I’m still sticking with the idea of mentioning your contribution in the README ;-) Seeing the video makes me genuinely happy.

**Comment by egdels** [comment]
Hello @Mokhyy . I’ve created release 2.4.1. It’s already published on the Play Store, and F-Droid should release it in the next few days. I’m keeping the issue open because of the other points.
