### ISSUE TITLE
Improve ocr and selection of text in processed pdf

### ISSUE THREAD

**Issue by teastrainer** [egdels/makeacopy#50]
If I export both the pdf with text and the text separately, the text file shows the recognized text (almost) correctly.

But it's not possible, to properly select the text in the pdf file. The marker for the selected text differs significantly from the visible text in the image. And even if the text is selected completely (CTRL+A), the text is shuffled. Please see the attached example files.

The first sentence from the textfile (correct):
In a bid to diversify its economy away from oil, he has opened Saudi Arabia up to the
outside world, taken the religious police off the streets, and allowed women to drive.

This sentence taken from the exported pdf (shuffled):
In bid to its from oil, a he has Saudi Arabia to the diversify economy away opened up 
outside world, taken the off the and allowed to drive. religious police streets, women 

**Image file for recognition:**
![Image](https://github.com/user-attachments/assets/f8165ad8-13a8-480a-8084-531bb6d7e7a4)

[text exported.txt](https://github.com/user-attachments/files/24280633/text.exported.txt)

[pdf exported with text.pdf](https://github.com/user-attachments/files/24280634/pdf.exported.with.text.pdf)

<img width="1360" height="196" alt="Image" src="https://github.com/user-attachments/assets/ec2f672d-6d2d-43cb-960d-578ea743d287" />

<img width="1260" height="155" alt="Image" src="https://github.com/user-attachments/assets/1a8203eb-bae9-4c6d-bb3b-480c8a8fe51d" />

**Comment by egdels** [comment]
Hi @teastrainer . I’m glad that you’re still interested in the project. Over the next period, I’d like to focus on the OCR recognition and try to improve this issue as well.

**Comment by egdels** [comment]
Hi @teastrainer 

nice catch.

Two examples:

[example_makeacopy_2_3_1.pdf](https://github.com/user-attachments/files/24315020/example_makeacopy_2_3_1.pdf)

[example_makeacopy_upcoming.pdf](https://github.com/user-attachments/files/24315025/example_makeacopy_upcoming.pdf)

Best regards, Christian

**Comment by egdels** [comment]
Hello @teastrainer . I’ve created a prototype for the next release. I’d really appreciate it if you could take another look and check whether the issue has been resolved. There is now also an option to load existing PDFs into MakeACopy, which may make testing easier. Thank you very much in advance for your help.

https://github.com/egdels/makeacopy/releases/tag/v2.4.0-rc2

**Comment by teastrainer** [comment]
It's much better now 👍️ Text is almost identical. But there are still some small deviations:

1st sentence
```
textfile: religious police
pdf: rehgious ponce
```

2nd sentence
```
textfile: But the kingdom's
pdf: But the kingdom&#39;s
```

And there are still offsets in width and height if you select the text in the pdf-file. The selection of "religious police" doesn't cover the corresponding text in the image (see below). Maybe that can't be fixed completely as I think this could be a general limitation with tesseract. I can live with that.

<img width="1477" height="190" alt="Image" src="https://github.com/user-attachments/assets/0d5fec55-a400-4f5b-a240-c6f34bcc72fc" />


[pdf exported with text2.pdf](https://github.com/user-attachments/files/24361355/pdf.exported.with.text2.pdf)
[text exported2.txt](https://github.com/user-attachments/files/24361356/text.exported2.txt)

**Comment by egdels** [comment]
Hi @teastrainer . Thank you very much! Once again, a small detail bug found.
The OCR layer in the PDF uses the post-processed version, while the OCR preview and the TXT contain the original one.
A classic case of over-engineering that made things worse. 😉

**Comment by egdels** [comment]
Hello @teastrainer . The issue should be fixed in 2.4.0. Version 2.4.1 is already available on the Play Store, and F-Droid will also release 2.4.1 soon. I think we can close the issue, right?

**Comment by teastrainer** [comment]
It's almost perfect, but I still get `&#39;` when copying an `apostrophe -> '` from the processed pdf. Can this be fixed, too?

**Comment by egdels** [comment]
Hello @teastrainer . Thanks! I’ll fix this in the next release, but it will take some time.

**Comment by egdels** [comment]
Hi @teastrainer, this should be fixed in v2.5.0 now:
https://github.com/egdels/makeacopy/releases/tag/v2.5.0

Thanks again for the detailed report.

**Comment by teastrainer** [comment]
Thank you! Characters are now identical in pdf and text file.

But I've recognized something else: In the text file there are double line breaks to separate the paragraphs. These are missing in the text layer of the pdf files. So I can see paragraphs in the text file, but if I copy the text from the pdf file, I only get one big paragraph.

Even worse: If I edit the text, the double line breaks get lost in the text file, too.

But the text is now as good as it can be, and this is a minor concern, so feel free to close the issue if you’d like.”

**Comment by egdels** [comment]
Hi @teastrainer

Long time no see 🙂 Hope you are still interested in the project.

I’m currently testing a completely new OCR engine based on PaddleOCR, which already fixes a lot of the text ordering and PDF layer issues internally.

The new version is now also available on Google Play as v4.1.0 - or as Paddle flavor from:

https://github.com/egdels/makeacopy/releases/download/v4.1.0-rc3/MakeACopy-v4.1.0-arm64-v8a-paddle-release.apk

If you want, I’d be very interested to hear how the OCR quality and PDF text selection compare on your documents.

**Comment by teastrainer** [comment]
Hi @egdels 

Yes, I'm still following your project! The heavy lifting, I do on my desktop pc, as here it's much easier to work with and the results are better (of course - because I use a commercial program 😉).

But if I have to recognize text from scans or photos on my phone, I only use MakeACopy 👍️. And I occasionally test the ocr after updates. And I think, the current one is better indeed compared to older releases:
- Especially almost all punctuation marks from the text are now in the results.
- But astonishingly, one row is missing now completely: "happen with no repercussions, really." - at the end of the 3rd paragraph.

When copying the text directly from the ocr-pdf, there's no improvement. Depending on the pdf viewer, the text looks different:

```
1) from the exported txt-file:

In a bid to diversify its economy away from oil, he has opened Saudi Arabia up to the
outside world, taken the religious police off the streets, and allowed women to drive.

2) pdf-reader 1 (double space characters):

In  a  bid  to  diversify  its  economy  away  from  oil,  he  has  opened  Saudi  Arabia  up  to  the 
outside  world,  taken  the  religious  police  off  the  streets,  and  allowed  women  to  drive. 

3) pdf-reader 2:

In
 a bid
 to
 diversify
 its
 economy
 away
 from
 oil,
...
```

**Comment by egdels** [comment]
Hi @teastrainer

Thank you very much for your feedback. This basically confirms my idea of removing Tesseract completely in favor of Paddle.

I can reproduce the missing paragraph issue as well, so I need to take a closer look at that.

Thanks again for taking the time to test it and for writing such a detailed response.

**Comment by egdels** [comment]
Hi @teastrainer,

I’ve created a new release candidate for MakeACopy 4.2.0:

https://github.com/egdels/makeacopy/releases/tag/v4.2.0-rc1

There is now also a new OCR option in the OCR settings called:

“Best Paddle-OCR”

This mode uses the new high-quality PaddleOCR pipeline and should especially improve the kinds of examples you reported in the past regarding text ordering and PDF text selection.

Thanks again for all your detailed feedback over time.

**Comment by teastrainer** [comment]
Thank you for your ongoing efforts to improve text recognition!

There has indeed been an improvement. The missing row is now back in the text. 

However, regardless of which PaddleOCR model I use (normal or best), the text is almost identical. In fact, the best model is slightly worse than the normal one, as it forgets some punctuation marks, e.g. at the end of the text.
PaddleOCR normal: `scrutiny".`
PaddleOCR best: `scrutiny"`

Aside from the punctiation marks, there's no difference. I think, thats because the image quality is almost perfect for ocr (high resolution and contrast, no distortion). Maybe the best model can shine with scans that have a lower quality.

And I still have problems to copy the text from the exported pdf and maybe I have found a hint to the possible cause. When using pdfgrep to search for a pattern in the files, I get the following output for the pdf from MakeACopy:
`In      a bid      to     diversify                 its     economy                 away           from              oil,     he has          opened               Saudi             Arabia       up      to the`

The result for the the same search pattern in the pdf from my commercial solution:
```In a bid to diversify its economy away from oil, he has opened Saudi Arabia up to the```

While some pdf readers (like Chromium or Firefox) sends the text without additional spaces to the clipboard, others (like Okular or Xreader) obviously interpret the several spaces between the words as line breaks, resulting in an output I have shown in my last response.

**Comment by egdels** [comment]
Thanks. I’ll take a closer look at this. For now I’ll keep the ticket open.

The TXT export already being clean is actually a very useful clue. That suggests the remaining issue is probably no longer the OCR itself, but rather how the invisible PDF text layer is written and interpreted by different PDF viewers.

Your testing and the pdfgrep examples were genuinely helpful here. You successfully dragged MakeACopy into the strange world of PDF whitespace philosophy ;-)

**Comment by egdels** [comment]
I attached a small example PDF for testing.

The current experimental PDF text layer does not position every OCR word individually anymore. Instead, each detected OCR line is written as one continuous hidden text run and horizontally scaled to the detected OCR line width.

This should improve copy/paste and text extraction, because PDF readers should no longer interpret large word gaps as multiple spaces or line breaks.

Limitation: this is still not full layout analysis. Non-line-based layouts such as multi-column pages, tables, forms, or separate text blocks may still require proper block/column detection.

[DOC_20260525_075304.pdf](https://github.com/user-attachments/files/28207789/DOC_20260525_075304.pdf)

**Comment by teastrainer** [comment]
Wow, that's what I was hoping for 👍️

With your test file, it is now much easier to select text in the resulting PDF, as there is hardly any difference between the marked (invisible) text and the underlying text in the picture anymore. You can also easily copy the text using any PDF viewer, resulting in text that you can work with!

As you mentioned, it would certainly be beneficial to have more sophisticated text recognition for non-line-based layouts. Perhaps you could implement such a solution in the future. I realise this will be difficult... But for now, I can live with this solution. I think that's sufficient for text recognition on the go.

Thanks for your painstaking efforts!

**Comment by egdels** [comment]
Hi. I’m still considering whether to turn this into a setting:

- Line-based text layer (default)
- Word-positioned text layer

In any case, this will be included in the next release.

Looking back at the ticket history, you’ve actually helped make the OCR much better over time. Thanks a lot for that.

**Comment by teastrainer** [comment]
I think, it's always good to have options, and I like the idea to make the line-based layer the default. I only asked for it, as for me, ocr is the most important feature when scanning pictures / documents. 

But you are the one who make the things happen - thanks for implementing this feature!

**Comment by teastrainer** [comment]
I've just tested the option for the multi-column layout text detection - working great 💪

However, ... In the following paragraph, there are two critical characters missing in the third column:

`Here is my query:`
`grep -r "lists.ubuntu.com"                  -> missing " /" at the end`
`home/edd/Documents/FCM25/`
`Weekly\news/                                -> missing space after "Weekly\"`

On the one hand, it's good enough for most use cases, on the other hand, if you want to copy code, it's relevant...

Over the time, the recognition capabilities of your app improved A LOT, thanks once again. Of course one (I) will always find errors, but I think, you can close this issue now if you want to 👍️

Testfile:
[fullcircle issue221_en-001.pdf](https://github.com/user-attachments/files/32630594/fullcircle.issue221_en-001.pdf)
